name = "vikas-project---cloudfare"
compatibility_date = "2025-01-01"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "INVENTORY_KV"
id = "339f838fdeb14c6abbc0a908f630536c"
